language: c

sudo: required
compiler:
  - gcc
env:
  global:
    - TARGETS=x86_64-softmmu
    - TEST_CMD=""
    - EXTRA_CONFIG=""
    # Development packages, EXTRA_PKGS saved for additional builds
    - CORE_PKGS="libusb-1.0-0-dev libiscsi-dev librados-dev libncurses5-dev"
    - NET_PKGS="libseccomp-dev libgnutls-dev libssh2-1-dev  libspice-server-dev libspice-protocol-dev libnss3-dev"
    - GUI_PKGS="libgtk-3-dev libvte-2.90-dev libsdl1.2-dev libpng12-dev libpixman-1-dev"
    - EXTRA_PKGS="autopoint"
git:
  submodules: false
before_install:
  - grep MemTotal /proc/meminfo
  - pwd
  - df -h
  - if [ "$NEED_IMAGE" == "Y" ]; then
    perl gdown.pl/gdown.pl "https://docs.google.com/uc?id=0B3tO_KfVdaBJV1Q5TG5PZjY0RDg&export=download" win10.qcow2;
    fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq ${CORE_PKGS} ${NET_PKGS} ${GUI_PKGS} ${EXTRA_PKGS}
  - sudo ldconfig -v
  - ls /usr/lib
  - git clone https://github.com/google/googletest.git
  - g++ -isystem googletest/googletest/include/ -Igoogletest/googletest -pthread -c googletest/googletest/src/gtest-all.cc -DGTEST_CREATE_SHARED_LIBRARY=1 -fPIC -shared -o libgtest.so
  - sudo mv libgtest.so /usr/lib/
  - sudo mv googletest/googletest/include/* /usr/include/
  # for memfrs testing
  - perl gdown.pl/gdown.pl "https://docs.google.com/uc?id=0Bw0V1Yd9ZxkESWNhbVVhMFRDMGc&export=download" type_definition.json;
  - perl gdown.pl/gdown.pl "https://docs.google.com/uc?id=0Bw0V1Yd9ZxkEWDh0VlNYbGNsYTA&export=download" global_variable.json;
before_script:
  - ./configure --target-list=${TARGETS} ${EXTRA_CONFIG}
script:
  - make -j4 && sh -c "${TEST_CMD}"
matrix: # define more builds here
  include:
    # enable all MBA extensions
    - env: EXTRA_CONFIG="--enable-mba-all"
           TEST_CMD="make mba-test"
      compiler: gcc
    # enable & run agent unit test
    - env: EXTRA_CONFIG="--enable-agent"
           TEST_CMD="make agent -C ext/ -f Makefile.test && ext/agent/test/bin/test_agent"
      compiler: gcc
    # enable & run dift unit test
    - env: EXTRA_CONFIG="--enable-dift"
           TEST_CMD="make dift -C ext/ -f Makefile.test && ext/dift/test/bin/test_dift"
      compiler: gcc
    # enable & run obhook unit test
    - env: EXTRA_CONFIG="--enable-obhook"
           TEST_CMD="make obhook -C ext -f Makefile.test && ext/obhook/test/bin/test_obhook"
      compiler: gcc
    # enable & run memfrs unit test
    - env: EXTRA_CONFIG="--enable-memfrs"
           TEST_CMD="make memfrs -C ext -f Makefile.test && ext/memfrs/test/bin/test_memfrs"
      compiler: gcc
    - env: EXTRA_CONFIG="--enable-tracer"
           TEST_CMD="make tracer -C ext -f Makefile.test && ext/tracer/test/bin/test_tracer"
      compiler: gcc    
